### PR TITLE
Fix LOL

### PR DESCRIPTION
**Pull request by thelucyclub**

### CODE REVIEW

**Comment by ImagicalGamer** [comment]
xD, this was my SG plug.

**Comment by thelucyclub** [comment]
Oh lol but still. It also crashes everytime the match ends. I assume this will be fixed soon though.

**Comment by remotevase** [comment]
It is likely...

**Comment by thelucyclub** [comment]
Good to hear! I look forward to using this plugin on my server. :+1: :smile:

**Pull request merged**
